### ISSUE TITLE
Kicked when setting perms in luck perms

### ISSUE THREAD

**Issue by ItzDepstRT** [LoneDev6/BungeePackFix#1]
/lp user NICK parent set Perms
And all players get his: 
![image](https://user-images.githubusercontent.com/77269898/148583143-ccc662d0-42ae-4d12-97e6-3aba88980e46.png)

**Comment by ItzDepstRT** [comment]
https://pastebin.com/KuHUtG4R

**Comment by ItzDepstRT** [comment]
Only kicks when chaneging default

**Comment by ItzDepstRT** [comment]
Yeah. I tried it few months back and it did the same thing. Im using this plugin mainly for oraxen.

**Comment by LoneDev6** [comment]
Oraxen has its own plugin, why not using it?
https://www.spigotmc.org/resources/%E2%9C%82%EF%B8%8F-bungee-pack-layer-optimize-resource-pack-sending.94978/

Anyway I cannot trigger the issue, it works fine for me

**Comment by ItzDepstRT** [comment]
Thier doesnt work. But its not issue from oraxen.

**Comment by LoneDev6** [comment]
> /lp user NICK parent set Perms And all players get his: ![image](https://user-images.githubusercontent.com/77269898/148583143-ccc662d0-42ae-4d12-97e6-3aba88980e46.png)

Anyway I need more info to find a fix for this.
i don't even have a log

**Comment by ItzDepstRT** [comment]
I will test it tommorow and send all needed things

**Comment by ItzDepstRT** [comment]
I tested it on basic server and it works. I apologize but. It doesnt want to work at my main server.
It loads when switching servers and i dont know why.

**Comment by ItzDepstRT** [comment]
Im sooo sorry! it my fault and i didnt realized i didnt had synced resourepacks from oraxen and they were not the same. So i synced it and it ports now.

**Comment by ItzDepstRT** [comment]
Well.. The loading works. But not the thing with the luckyperms

**Comment by ItzDepstRT** [comment]
Here is the log from water fall. This happend after i asigned rank with higher perms than default at server survival.

https://pastebin.com/h2nnzT46

**Comment by LoneDev6** [comment]
I think there is something misconfigured, anyway please avoid sending all these messages, edit your main message instead.
Thanks

**Comment by ItzDepstRT** [comment]
But what misconfigured?

**Comment by ItzDepstRT** [comment]
Can it be becouse my luck perms databases arent synced?

**Comment by ItzDepstRT** [comment]
Found the plugin that does it. Its an TAB from neznamy.. Its very popular... Any idea?

**Comment by ItzDepstRT** [comment]
So yeah. It was in the newest version of tab fixed i guess.. I apologize
