### ISSUE TITLE
The plugin still loads the texturepack agai neven tho they are same.

### ISSUE THREAD

**Issue by DEPSTRCZ** [LoneDev6/BungeePackFix#14]
Here is the logs with debug https://pastebin.com/K6j4sY8i

**Comment by ItzDepstRT** [comment]
Latest waterfall and plugin

**Comment by PystoyPlayer** [comment]
same

**Comment by LoneDev6** [comment]
This is not made for oraxen, anyway the pack hash and url are clearly different.

`url='http://atlas.oraxen.com/pack.zip?id=c515ea91b232904eec6681a1a64bee557430f295', hash=c515ea91b232904eec6681a1a64bee557430f295,`


`{url='http://atlas.oraxen.com/pack.zip?id=6edd270cdcc8045b58a88372f3294cc22cce0f2a', hash=6edd270cdcc8045b58a88372f3294cc22cce0f2a`
