### ISSUE TITLE
[Feature Request] Add option for urls of packs that should be skipped

### ISSUE THREAD

**Issue by DEPSTRCZ** [LoneDev6/BungeePackFix#15]
Basicly this will make the plugin more legacy for more plugins that are doing something with resurcepacks..

I mean by that that there should be new option in config where user can specify what urls of resourcepack should be skipped too 
even if they are different.

*Im sorry if something like this already exists but  there is not any documentation..

**Comment by LoneDev6** [comment]
Sorry I don't understand what you mean
