### ISSUE TITLE
1.19.3

### ISSUE THREAD

**Issue by ColorsASD** [LoneDev6/BungeePackFix#16]
Please update 1.19.3!
ViaVersion is not compatible with this.
This was also the error with version 1.19.2, so the server keeps quiting with: server_went_down (proxy_message)

**Comment by LoneDev6** [comment]
Provide valid bungeecord and spigot servers logs.
Make sure to update Viaversion, Viabackwards and Protocollib if you have them.

**Comment by LoneDev6** [comment]
Hello?

**Comment by nhanledev** [comment]
Waterfall build 510
Paper 1.19.2 build 307
Viaversion/ViaBackward 4.5.1
ProtocolLib build 607

1.19.3 client is kicked when switching world, error on proxy:
```
could not decode packet! io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
```

**Comment by ColorsASD** [comment]
Sorry I wasn't at home, but I see it's already solved.
