### ISSUE TITLE
Packs are identical however still reload

### ISSUE THREAD

**Issue by NoobcoreNetwork** [LoneDev6/BungeePackFix#2]
![explorer_wh2Pw4SquC](https://user-images.githubusercontent.com/62724418/150001350-cd1d2050-987d-4d30-ae3a-65eb043a2140.png)

Hey! So last night I had some issues with my pack, and had to restore a backup and change the port for upload.
I went from 8322 to 8350 on the port, I run the pack on survival and lobby servers, same pack using bungeepackfix

Bungeepack fix used to work, But since i had to restore a backup and change port its no longer working,
Both on the same version of IA, (2.5.0-beta) And bungeepackfix is on bungeecord obviously,

Both use the exact same config file, its a complete clone of the IA folders on each server.
the first image shows the files are exactly identical down to the exact file count. (there is a slight difference in the bytes on one server could that be the issue?) Its a copy paste of the other folder so not sure why its done that)

What exactly tells bungeepack fix that 'these are the same packs' so skip download? 

Thanks!

**Comment by NoobcoreNetwork** [comment]
Think i found out my issue,

on the lobby I had apply-on-join: true 
I assume this is suppose to be set to false? as the apply-on-join will overide bungeepackfix?

**Comment by LoneDev6** [comment]
The pack must have the same URL to be considered equal.

**Comment by NoobcoreNetwork** [comment]
> The pack must have the same URL and same FORCED value to be considered equal.
> https://github.com/LoneDev6/BungeePackFix/blob/main/src/main/java/dev/lone/bungeepackfix/libs/packetlistener/packets/RespackSendPacketOut.java#L157

Oh weird. They both are self hosted on the same port and both forced=true and it reloaded the pack every time going from lobby to survival.

The only solution for me was to set the lobby to have apply on join: true and false on survival

Then going from lobby to survival works fine.

Then force the lobby server on first join

**Comment by NoobcoreNetwork** [comment]
Might be worth mentioning it only happened when I changed to 1.18.1

**Comment by LoneDev6** [comment]
Check if:
- the URL is IDENTICAL: http/https, address, port.
- if another plugin is trying to apply a resourcepack too

**Comment by NoobcoreNetwork** [comment]
> Check if:
> - the URL is IDENTICAL: http/https, address, port.
> - if another plugin is trying to apply a resourcepack too

100% I'm self hosting with my dedi ip and same port. Going directly to the link aka 192.168.1.1:2025 (example) downloads the pack

Still no luck

**Comment by NoobcoreNetwork** [comment]
> > Check if:
> > - the URL is IDENTICAL: http/https, address, port.
> > - if another plugin is trying to apply a resourcepack too
> 
> 100% I'm self hosting with my dedi ip and same port. Going directly to the link aka 192.168.1.1:2025 (example) downloads the pack
> 
> Still no luck 

It worked on 1.17.1 but broke when I updated to 1.18.1

**Comment by NoobcoreNetwork** [comment]
24.01 02:10:34 [Server] ERROR [ItemsAdder] 
24.01 02:10:34 [Server] ERROR [ItemsAdder] Error initializing self-host: Address already in use
24.01 02:10:34 [Server] ERROR [ItemsAdder] Make sure the port '8155' is not used by another process.
24.01 02:10:34 [Server] ERROR [ItemsAdder] 
24.01 02:10:34 [Server] INFO [ItemsAdder] [Host] Started self-host webserver on port: 8155

I did some investigating and noticed, This error seems to happen when they both are on the same port?

**Comment by NoobcoreNetwork** [comment]
24.01 02:10:34 [Server] ERROR [ItemsAdder] 
24.01 02:10:34 [Server] ERROR [ItemsAdder] Error initializing self-host: Address already in use
24.01 02:10:34 [Server] ERROR [ItemsAdder] Make sure the port '8155' is not used by another process.
24.01 02:10:34 [Server] ERROR [ItemsAdder] 
24.01 02:10:34 [Server] INFO [ItemsAdder] [Host] Started self-host webserver on port: 8155

I did some investigating and noticed, This error seems to happen when they both are on the same port?

**Comment by LoneDev6** [comment]
> Make sure the port '8155' is not used by another process.
