### ISSUE TITLE
Small bug | About Velocity update

### ISSUE THREAD

**Issue by Felson999** [LoneDev6/BungeePackFix#20]
It's a bug, I don't need to explain. I changed my config and now it works. Change in your code. Thanks for the wonderful plugin!
![Без імsdfhgені](https://user-images.githubusercontent.com/52543528/210188509-44a66b0a-1a6e-4fa1-8940-6f15cad01181.png)
![Без імеasdні](https://user-images.githubusercontent.com/52543528/210188510-5054c6af-e493-476f-b831-0191d04cb583.png)

**Comment by LoneDev6** [comment]
@YoSoyVillaa

**Comment by YoSoyVillaa** [comment]
Sorry for the mistake and thanks @Felson999 for reporting it.

**Comment by LoneDev6** [comment]
Ty for fixing
