### ISSUE TITLE
The problem with pom

### ISSUE THREAD

**Issue by Coquettishpig** [LoneDev6/BungeePackFix#23]
The core used by pom is local, but it seems to be idiosyncratic, I downloaded the core play to compile him, please can I not use the local path

**Comment by zHackeed** [comment]
Change the local path to your local path providing the waterfall jar, as the bungeecord/waterfall packets are not exposed on the api, you need the waterfall jar as a local path dependency.


Hope that helps.

**Comment by Coquettishpig** [comment]
> 将本地路径更改为提供瀑布罐的本地路径，因为蹦极/瀑布数据包不会在 API 上公开。您需要瀑布罐作为本地路径依赖项。
> 
> 如果你想要一个编译版本，你可以在[发布](https://github.com/LoneDev6/BungeePackFix/releases/tag/1.0.9)或插口上得到一个。
> 
> 希望有帮助。

but，
![87Q$PA1@8PBVBKY98~PUWDN](https://user-images.githubusercontent.com/107100449/212589529-08483f92-4b83-4a6b-90cc-a518db4ba9c8.png)
I am using the latest waterfall and it does not build, can you please send me a copy of waterfall that works, I need it badly, my discord is Coquettishpig#5454

**Comment by zHackeed** [comment]
> > 将本地路径更改为提供瀑布罐的本地路径，因为蹦极/瀑布数据包不会在 API 上公开。您需要瀑布罐作为本地路径依赖项。
> > 如果你想要一个编译版本，你可以在[发布](https://github.com/LoneDev6/BungeePackFix/releases/tag/1.0.9)或插口上得到一个。
> > 希望有帮助。
> 
> but， ![87Q$PA1@8PBVBKY98~PUWDN](https://user-images.githubusercontent.com/107100449/212589529-08483f92-4b83-4a6b-90cc-a518db4ba9c8.png) I am using the latest waterfall and it does not build, can you please send me a copy of waterfall that works, I need it badly, my discord is Coquettishpig#5454

`
        <dependency>
            <groupId>libs</groupId>
            <artifactId>Waterfall</artifactId>
            <version>1.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/waterfall-1.19-510.jar</systemPath>
        </dependency>
`

On your base project you need to create a folder named libs and move the waterfall jar to it. Should work for you. (remember to .gitignore it).
