### ISSUE TITLE
Configuration property to ignore servers

### ISSUE THREAD

**Issue by Coquettishpig** [LoneDev6/BungeePackFix#25]
After using this plug-in, it will cause the low version can not enter the high version server, prompting the material package can not be decoded, hope it is compatible with ViaVersion and ViaBackwards

**Comment by Coquettishpig** [comment]
![image](https://user-images.githubusercontent.com/107100449/212531567-8e22cab2-4e7d-404a-b6e5-70e903ccb2c5.png)

**Comment by LoneDev6** [comment]
Please be more specific.
Which server versions and which client version?

**Comment by Coquettishpig** [comment]
> 

1.18.2 purpur
and lunar 1.8.9

**Comment by LoneDev6** [comment]
Why are you trying to join a 1.18.2 server which runs ItemsAdder with a 1.8.9 client?
You're not supposed to play with that old version. You won't see any of the game assets.

**Comment by Coquettishpig** [comment]
> 为什么要尝试加入使用 1.8.9 客户端运行 ItemsAdder 的 1.18.2 服务器？你不应该玩那个旧版本。您不会看到任何游戏资产。

That's why I need the whitelist system for disabling him in low version servers, because I am prompted for this when I load material packages on other servers using the configuration in server.properties, this server I am not using itemsadder, and when I uninstall bungeepackfix there is no problem with this, so I need a whitelist system to prevent this separate server material pack from syncing

**Comment by LoneDev6** [comment]
https://github.com/LoneDev6/BungeePackFix/releases/tag/1.1.0-r2-pre-1

```yml
ignored_servers:
  - ignored_1
  - ignored_2
```

**Comment by Coquettishpig** [comment]
> https://github.com/LoneDev6/BungeePackFix/releases/tag/1.1.0-r2-pre-1
> 
> ```yaml
> ignored_servers:
>   - ignored_1
>   - ignored_2
> ```

good,I will test him soon.
