### ISSUE TITLE
Hope to support disabling some servers

### ISSUE THREAD

**Issue by Coquettishpig** [LoneDev6/BungeePackFix#26]
I hope to support whitelist system, some of my servers do not want to synchronize the server material package

**Comment by Coquettishpig** [comment]
I bought itemsAdder, I really need this feature, but adding your discord you did not agree, thank you very much, part of my server does not want to use the functionality of this plugin, but another part of the server needs it, the staff is very kind, I really need this feature

**Comment by LoneDev6** [comment]
I'll implement this feature but it breaks the purpose of the plugin and possibly cause some confusion.

**Comment by Coquettishpig** [comment]
> 我将实现此功能，但它破坏了插件的目的，并可能导致一些混乱。

No problem, I really need him, you can set whether this feature is on or not, thanks a lot

**Comment by Coquettishpig** [comment]
> I'll implement this feature but it breaks the purpose of the plugin and possibly cause some confusion.

It allows some servers to turn off resource packet sync, because there are some servers I don't use itemadder, and I don't think I should be the only one who needs it, so I think this update is the right one, there are definitely people who will like it as much as I do, thank you very much!
