### ISSUE TITLE
Color characters & not working

### ISSUE THREAD

**Issue by Coquettishpig** [LoneDev6/BungeePackFix#28]
![image](https://user-images.githubusercontent.com/107100449/213134131-b6449e3e-4c57-4e38-879e-dee6d105de6b.png)
![image](https://user-images.githubusercontent.com/107100449/213134147-9240c785-b80a-452a-871a-4388a558a39f.png)

**Comment by LoneDev6** [comment]
disable minimessage support.
or use minimessage way of coloring.
example: `<gold>your message`
