### ISSUE TITLE
Repository should mention usage of internal code (And possible setup guidelines)

### ISSUE THREAD

**Issue by Andre601** [LoneDev6/BungeePackFix#3]
The plugin seems to utilize internal code from BungeeCord.

This should be mentioned within the README or somewhere else, so that potential contributors are aware of this and can setup the environment properly to avoid issues like below:

![image](https://user-images.githubusercontent.com/11576465/158587496-4875413b-6658-4d89-ae34-e8700c8961b0.png)

**Comment by LoneDev6** [comment]
You have to include internal Bungeecord code in your IDE.
I just added the JAR as dependency in my IDE to be able to resolve these imports.
