### ISSUE TITLE
This plugin is great but it's not working on 1.20.1 can you fix it please ! :)

### ISSUE THREAD

**Issue by hed516** [LoneDev6/BungeePackFix#34]
This plugin is great but it's not working on 1.20.1 can you fix it please ! :)

**Comment by LoneDev6** [comment]
Please add some details, another user tested the old 1.1.1 version on Minecraft 1.20.1 and said it works fine.
On the other hand the new version 1.1.2 is not working on Minecraft 1.20.1.
