### ISSUE TITLE
[Bug] Can't connect server when using 1.19 client

### ISSUE THREAD

**Issue by ArtifactyNight** [LoneDev6/BungeePackFix#4]
![image](https://user-images.githubusercontent.com/53427253/174129341-d2096272-9d6a-401f-b6f0-a52d4d52ab0c.png)

I'm using Waterfall 1.19 Build 496

Tested with 1.18.2 client is work fine 
but 1.19 client is can't connect to the server

**Comment by ItzDepstRT** [comment]
Same problem here

**Comment by ItzDepstRT** [comment]
Also when using fallback server plugin
If BungeePack fix plugin is removed everything works

**Comment by WongIong** [comment]
Same here, but with different error

**Comment by ItzDepstRT** [comment]
Same problem but all clients cant connect

**Comment by ItzDepstRT** [comment]
safe to say this plugin does not work 100% on 1.19

**Comment by WongIong** [comment]
![image](https://user-images.githubusercontent.com/36799194/174352807-5b1ac9ca-3d7b-45c5-bc5e-d2938aa05082.png)
