### ISSUE TITLE
New logic

### ISSUE THREAD

**Issue by LoneDev6** [LoneDev6/BungeePackFix#40]
I think would be better to basically just provide the resourcepack links in the BungeepackFix configuration.
This allows you to easily configure your resourcepack links for each one of the servers without having to open the ItemsAdder configuration on each server.

Let me know what you think

**Comment by Adreez** [comment]
I think it would be much easier to work with. I'm really keen on that idea.

**Comment by LoneDev6** [comment]
This idea is flawed as self-host won't work because the URL is changing on each /iazip execution, so the bungeecord server must be manually updated each time and i doubt people want to do that.
