### ISSUE TITLE
1.20.2 resource pack disabled.

### ISSUE THREAD

**Issue by happy704** [LoneDev6/BungeePackFix#47]
In version 1.20.1, even when downloading the resource pack on server1 and connecting to server2, the resource pack remains applied. However, when connecting to the server with version 1.20.2, there is an issue where the resource pack gets disabled.

BungeePackFix 1.1.4
git-Paper-62 (MC: 1.20.1)
ViaVersion 4.8.1

**Comment by LoneDev6** [comment]
Seems a duplicate if this #44
