### ISSUE TITLE
1.5.5-dev kicks player if item is inserted into anvil

### ISSUE THREAD

**Issue by petulikan1** [LoneDev6/BungeePackFix#54]
Hey there, I've been testing this new dev version of BungeePackFix and I've found an interesting bug.

I've enabled the "debug" option in the BungeePackFix config - visible in both videos.

With the 1.1.5 - Dev version, if player inserts an item into anvil, they get kicked out without any error or any debug message.
Here's a link to video showing such behaviour: https://youtu.be/e8GpcC3mxLY

Fortunately with version 1.4.4, such behaviour isn't happening, as shown in the video, if player inserts an item into the anvil, nothing happens as supposed. https://youtu.be/Cj0poxsLWFk

**Comment by kamber5** [comment]
Same issue on our server.
Would be great if it gets patched soon.

**Comment by LoneDev6** [comment]
I have no info about your servers versions and client versions.

**Comment by kamber5** [comment]
All of my servers are on 1.20.1.
[08:49:46 INFO]: This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version

Players can join from 1.16.x to 1.20.x (Only 1.20.2 is blocked from joining)

**Comment by petulikan1** [comment]
In both the videos, I've used the 1.20.1 client, for some strange reason the problematic dev version doesn't kick players that are using 1.20.3

As for the server - We're running Waterfall (latest) as a proxy and then Purpur (1.20.1) for that server where the video was taken

**Comment by kamber5** [comment]
Hopefully this gets patched soon, because BungeePackFix with ItemsAdder is a must on Bungee servers.

**Comment by wellnesscookie** [comment]
Hi! Same problem here as @petulikan1 described. Could you please look into it? Thanks!

**Comment by petulikan1** [comment]
Hey everyone, good news. I've found a fix for this issue, I'll be posting later PR so it can be resolved asap.
