### ISSUE TITLE
BungeePackFix 1.0.4 error on load

### ISSUE THREAD

**Issue by LuluxClient** [LoneDev6/BungeePackFix#9]
After updating everything (bungee itemsadder etc...) I'm getting this error on load: https://pastebin.com/6UnN9swA

**Comment by SwartZCoding** [comment]
Same error here @LoneDev6. I approve. 

https://gyazo.com/3e52a958d39cadcfd15b252b874328ea

**Comment by LoneDev6** [comment]
Maybe another Bungeecord plugin already registered the pack mapping and this causes this issue?

**Comment by LuluxClient** [comment]
Hey check the PR apparently Swartz Fixed it.

**Comment by LoneDev6** [comment]
Perfect! Already approved
